# Generated by Django 3.1.4 on 2020-12-17 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheatexam_question', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='status',
            field=models.CharField(choices=[('poor', 'کم'), ('high', 'زیاد')], default=False, max_length=20),
        ),
    ]
