# Generated by Django 3.1.4 on 2020-12-19 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheatexam_question', '0005_auto_20201219_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='iknow',
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
