# Generated by Django 3.1.4 on 2020-12-22 16:49

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheatexam_question', '0006_auto_20201219_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='creator',
            field=models.CharField(default=django.contrib.auth.validators.UnicodeUsernameValidator(), max_length=120, null=True),
        ),
    ]
