# Generated by Django 3.1.4 on 2020-12-22 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cheatexam_question', '0007_question_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='creator',
        ),
    ]
