# Generated by Django 3.1.4 on 2020-12-22 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cheatexam_question', '0009_question_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='owner',
        ),
    ]
