# Generated by Django 3.1.4 on 2020-12-23 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cheatexam_forms', '0001_initial'),
        ('cheatexam_question', '0017_auto_20201222_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='froms',
            field=models.ForeignKey(default=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='cheatexam_forms.forms'),
        ),
    ]
