# Generated by Django 3.1.4 on 2020-12-23 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cheatexam_question', '0018_question_froms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='froms',
        ),
    ]
