# Generated by Django 3.1.4 on 2020-12-23 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cheatexam_forms', '0002_auto_20201223_1122'),
        ('cheatexam_question', '0019_remove_question_froms'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='froms',
            field=models.ForeignKey(default=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='cheatexam_forms.forms'),
        ),
    ]
