# Generated by Django 3.1.4 on 2020-12-23 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cheatexam_question', '0021_auto_20201223_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='froms',
        ),
    ]
