# Generated by Django 3.1.4 on 2020-12-23 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cheatexam_forms', '0002_auto_20201223_1122'),
        ('cheatexam_question', '0022_remove_question_froms'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='form',
            field=models.ForeignKey(default='class', on_delete=django.db.models.deletion.CASCADE, to='cheatexam_forms.forms'),
            preserve_default=False,
        ),
    ]
