# Generated by Django 3.1.4 on 2020-12-23 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cheatexam_forms', '0008_remove_forms_user'),
        ('cheatexam_question', '0025_auto_20201223_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='form',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='cheatexam_forms.forms'),
            preserve_default=False,
        ),
    ]
