# Generated by Django 3.1.4 on 2020-12-23 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheatexam_question', '0026_question_form'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='id',
        ),
        migrations.AlterField(
            model_name='question',
            name='message',
            field=models.TextField(primary_key=True, serialize=False, verbose_name='سوال'),
        ),
    ]
