# Generated by Django 3.1.4 on 2020-12-23 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheatexam_forms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forms',
            name='id',
        ),
        migrations.AlterField(
            model_name='forms',
            name='slug',
            field=models.SlugField(primary_key=True, serialize=False, unique=True),
        ),
    ]
