# Generated by Django 3.1.4 on 2020-12-23 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cheatexam_forms', '0002_auto_20201223_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='forms',
            name='user',
            field=models.ForeignKey(default='sahand', on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
