# Generated by Django 3.1.4 on 2020-12-23 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cheatexam_forms', '0003_forms_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forms',
            name='user',
        ),
    ]
