# Generated by Django 3.1.4 on 2021-01-07 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cheatexam_forms', '0009_forms_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forms',
            name='password',
        ),
    ]
