# Generated by Django 3.1.4 on 2021-01-07 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cheatexam_question', '0029_remove_question_form'),
        ('cheatexam_forms', '0010_remove_forms_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='forms',
            name='ask',
            field=models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, to='cheatexam_question.question'),
            preserve_default=False,
        ),
    ]
